version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11

    working_directory: ~/simply-molkky

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: yarn lint
      - run:
          name: Unit tests
          command: yarn test:unit
      - run:
          name: Send coverage to Coveralls
          command: cat ./reports/coverage/unit/lcov.info | ./node_modules/coveralls/bin/bincoveralls.js
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports
