version: 2
jobs:
  checkout_code:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/simply-molkky
    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/simply-molkky

  install_dependencies:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/simply-molkky
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run: yarn install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

  lint_test:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/simply-molkky
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint test
          command: yarn lint

  unit_test:
    docker:
      - image: circleci/node:8.11
    working_directory: ~/simply-molkky
    steps:
      - restore_cache:
          keys:
            - v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Unit tests
          command: yarn test:unit
      - run:
          name: Send coverage to Coveralls
          command: yarn coverage:upload
      - store_artifacts:
          path: reports
      - store_test_results:
          path: reports

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  build-deploy:
    jobs:
      - checkout_code
      - install_dependencies:
          requires:
            - checkout_code
      - lint_test:
          requires:
            - install_dependencies
      - unit_test:
          requires:
            - install_dependencies
      - deploy:
          requires:
            - lint_test
            - unit_test
          filters:
            branches:
              only: master
